In [3]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter

from langchain_chroma import Chroma

from langchain_community.embeddings import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [5]:
import pandas as pd
books = pd.read_csv("books_cleaned.csv")

In [6]:
books["tagged_description"]

0       9780002005883: A NOVEL THAT READERS and critic...
1       9780002261982: A new 'Christie for Christmas' ...
2       9780006178736: A memorable, mesmerizing heroin...
3       9780006280897: Lewis' work on the nature of lo...
4       9780006280934: "In The Problem of Pain, C.S. L...
                              ...
5192    9788172235222: On A Train Journey Home To Nort...
5193    9788173031014: This book tells the tale of a m...
5194    9788179921623: Wisdom to Create a Life of Pass...
5195    9788185300535: This collection of the timeless...
5196    9789027712059: Since the three volume edition ...
Name: tagged_description, Length: 5197, dtype: object

In [8]:
books["tagged_description"].to_csv("tagged_description.txt",
                            sep="\n",
                            index=False,
                            header=False)

In [13]:
raw_documents = TextLoader("C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=50, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1169, which is longer than the specified 500
Created a chunk of size 1215, which is longer than the specified 500
Created a chunk of size 961, which is longer than the specified 500
Created a chunk of size 844, which is longer than the specified 500
Created a chunk of size 882, which is longer than the specified 500
Created a chunk of size 1089, which is longer than the specified 500
Created a chunk of size 1190, which is longer than the specified 500
Created a chunk of size 514, which is longer than the specified 500
Created a chunk of size 753, which is longer than the specified 500
Created a chunk of size 729, which is longer than the specified 500
Created a chunk of size 722, which is longer than the specified 500
Created a chunk of size 1268, which is longer than the specified 500
Created a chunk of size 682, which is longer than the specified 500
Created a chunk of size 554, which is longer than the specified 500
Created a chunk of size 522, which is longer than the specified 500
Created a chunk of size 788, which is longer than the specified 500
Created a chunk of size 565, which is longer than the specified 500
Created a chunk of size 524, which is longer than the specified 500
Created a chunk of size 534, which is longer than the specified 500
Created a chunk of size 560, which is longer than the specified 500
Created a chunk of size 564, which is longer than the specified 500
Created a chunk of size 596, which is longer than the specified 500
Created a chunk of size 615, which is longer than the specified 500
Created a chunk of size 888, which is longer than the specified 500
Created a chunk of size 694, which is longer than the specified 500
Created a chunk of size 2011, which is longer than the specified 500
Created a chunk of size 521, which is longer than the specified 500
Created a chunk of size 648, which is longer than the specified 500
Created a chunk of size 779, which is longer than the specified 500
Created a chunk of size 687, which is longer than the specified 500
Created a chunk of size 549, which is longer than the specified 500
Created a chunk of size 1226, which is longer than the specified 500
Created a chunk of size 1185, which is longer than the specified 500
Created a chunk of size 1215, which is longer than the specified 500
Created a chunk of size 1192, which is longer than the specified 500
Created a chunk of size 1058, which is longer than the specified 500
Created a chunk of size 689, which is longer than the specified 500
Created a chunk of size 877, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 724, which is longer than the specified 500
Created a chunk of size 527, which is longer than the specified 500
Created a chunk of size 522, which is longer than the specified 500
Created a chunk of size 900, which is longer than the specified 500
Created a chunk of size 1271, which is longer than the specified 500
Created a chunk of size 559, which is longer than the specified 500
Created a chunk of size 1636, which is longer than the specified 500
Created a chunk of size 778, which is longer than the specified 500
Created a chunk of size 717, which is longer than the specified 500
Created a chunk of size 515, which is longer than the specified 500
Created a chunk of size 959, which is longer than the specified 500
Created a chunk of size 1133, which is longer than the specified 500
Created a chunk of size 1326, which is longer than the specified 500
Created a chunk of size 852, which is longer than the specified 500
Created a chunk of size 802, which is longer than the specified 500
Created a chunk of size 1120, which is longer than the specified 500
Created a chunk of size 837, which is longer than the specified 500
Created a chunk of size 733, which is longer than the specified 500
Created a chunk of size 1196, which is longer than the specified 500
Created a chunk of size 711, which is longer than the specified 500
Created a chunk of size 774, which is longer than the specified 500
Created a chunk of size 767, which is longer than the specified 500
Created a chunk of size 768, which is longer than the specified 500
Created a chunk of size 717, which is longer than the specified 500
Created a chunk of size 2013, which is longer than the specified 500
Created a chunk of size 1287, which is longer than the specified 500
Created a chunk of size 1232, which is longer than the specified 500
Created a chunk of size 730, which is longer than the specified 500
Created a chunk of size 751, which is longer than the specified 500
Created a chunk of size 1243, which is longer than the specified 500
Created a chunk of size 913, which is longer than the specified 500
Created a chunk of size 845, which is longer than the specified 500
Created a chunk of size 1127, which is longer than the specified 500
Created a chunk of size 1074, which is longer than the specified 500
Created a chunk of size 1319, which is longer than the specified 500
Created a chunk of size 2835, which is longer than the specified 500
Created a chunk of size 571, which is longer than the specified 500
Created a chunk of size 1142, which is longer than the specified 500
Created a chunk of size 1005, which is longer than the specified 500
Created a chunk of size 716, which is longer than the specified 500
Created a chunk of size 711, which is longer than the specified 500
Created a chunk of size 2511, which is longer than the specified 500
Created a chunk of size 955, which is longer than the specified 500
Created a chunk of size 640, which is longer than the specified 500
Created a chunk of size 524, which is longer than the specified 500
Created a chunk of size 794, which is longer than the specified 500
Created a chunk of size 1423, which is longer than the specified 500
Created a chunk of size 1084, which is longer than the specified 500
Created a chunk of size 1145, which is longer than the specified 500
Created a chunk of size 1269, which is longer than the specified 500
Created a chunk of size 791, which is longer than the specified 500
Created a chunk of size 1087, which is longer than the specified 500
Created a chunk of size 875, which is longer than the specified 500
Created a chunk of size 877, which is longer than the specified 500
Created a chunk of size 807, which is longer than the specified 500
Created a chunk of size 1813, which is longer than the specified 500
Created a chunk of size 1831, which is longer than the specified 500
Created a chunk of size 1065, which is longer than the specified 500
Created a chunk of size 956, which is longer than the specified 500
Created a chunk of size 1181, which is longer than the specified 500
Created a chunk of size 1285, which is longer than the specified 500
Created a chunk of size 1643, which is longer than the specified 500
Created a chunk of size 758, which is longer than the specified 500
Created a chunk of size 1931, which is longer than the specified 500
Created a chunk of size 873, which is longer than the specified 500
Created a chunk of size 2009, which is longer than the specified 500
Created a chunk of size 2286, which is longer than the specified 500
Created a chunk of size 1004, which is longer than the specified 500
Created a chunk of size 578, which is longer than the specified 500
Created a chunk of size 1143, which is longer than the specified 500
Created a chunk of size 558, which is longer than the specified 500
Created a chunk of size 1144, which is longer than the specified 500
Created a chunk of size 1087, which is longer than the specified 500
Created a chunk of size 1484, which is longer than the specified 500
Created a chunk of size 1136, which is longer than the specified 500
Created a chunk of size 723, which is longer than the specified 500
Created a chunk of size 669, which is longer than the specified 500
Created a chunk of size 766, which is longer than the specified 500
Created a chunk of size 607, which is longer than the specified 500
Created a chunk of size 571, which is longer than the specified 500
Created a chunk of size 966, which is longer than the specified 500
Created a chunk of size 858, which is longer than the specified 500
Created a chunk of size 1033, which is longer than the specified 500
Created a chunk of size 653, which is longer than the specified 500
Created a chunk of size 734, which is longer than the specified 500
Created a chunk of size 526, which is longer than the specified 500
Created a chunk of size 1016, which is longer than the specified 500
Created a chunk of size 971, which is longer than the specified 500
Created a chunk of size 689, which is longer than the specified 500
Created a chunk of size 545, which is longer than the specified 500
Created a chunk of size 932, which is longer than the specified 500
Created a chunk of size 565, which is longer than the specified 500
Created a chunk of size 855, which is longer than the specified 500
Created a chunk of size 716, which is longer than the specified 500
Created a chunk of size 750, which is longer than the specified 500
Created a chunk of size 713, which is longer than the specified 500
Created a chunk of size 1089, which is longer than the specified 500
Created a chunk of size 724, which is longer than the specified 500
Created a chunk of size 705, which is longer than the specified 500
Created a chunk of size 1913, which is longer than the specified 500
Created a chunk of size 623, which is longer than the specified 500
Created a chunk of size 560, which is longer than the specified 500
Created a chunk of size 557, which is longer than the specified 500
Created a chunk of size 625, which is longer than the specified 500
Created a chunk of size 2617, which is longer than the specified 500
Created a chunk of size 1581, which is longer than the specified 500
Created a chunk of size 995, which is longer than the specified 500
Created a chunk of size 848, which is longer than the specified 500
Created a chunk of size 1531, which is longer than the specified 500
Created a chunk of size 2031, which is longer than the specified 500
Created a chunk of size 1620, which is longer than the specified 500
Created a chunk of size 699, which is longer than the specified 500
Created a chunk of size 823, which is longer than the specified 500
Created a chunk of size 844, which is longer than the specified 500
Created a chunk of size 1190, which is longer than the specified 500
Created a chunk of size 509, which is longer than the specified 500
Created a chunk of size 664, which is longer than the specified 500
Created a chunk of size 1283, which is longer than the specified 500
Created a chunk of size 1269, which is longer than the specified 500
Created a chunk of size 1278, which is longer than the specified 500
Created a chunk of size 1057, which is longer than the specified 500
Created a chunk of size 785, which is longer than the specified 500
Created a chunk of size 970, which is longer than the specified 500
Created a chunk of size 614, which is longer than the specified 500
Created a chunk of size 758, which is longer than the specified 500
Created a chunk of size 964, which is longer than the specified 500
Created a chunk of size 844, which is longer than the specified 500
Created a chunk of size 787, which is longer than the specified 500
Created a chunk of size 649, which is longer than the specified 500
Created a chunk of size 985, which is longer than the specified 500
Created a chunk of size 800, which is longer than the specified 500
Created a chunk of size 1164, which is longer than the specified 500
Created a chunk of size 1059, which is longer than the specified 500
Created a chunk of size 876, which is longer than the specified 500
Created a chunk of size 818, which is longer than the specified 500
Created a chunk of size 756, which is longer than the specified 500
Created a chunk of size 570, which is longer than the specified 500
Created a chunk of size 629, which is longer than the specified 500
Created a chunk of size 869, which is longer than the specified 500
Created a chunk of size 621, which is longer than the specified 500
Created a chunk of size 622, which is longer than the specified 500
Created a chunk of size 1085, which is longer than the specified 500
Created a chunk of size 2763, which is longer than the specified 500
Created a chunk of size 1034, which is longer than the specified 500
Created a chunk of size 759, which is longer than the specified 500
Created a chunk of size 774, which is longer than the specified 500
Created a chunk of size 635, which is longer than the specified 500
Created a chunk of size 1011, which is longer than the specified 500
Created a chunk of size 1065, which is longer than the specified 500
Created a chunk of size 796, which is longer than the specified 500
Created a chunk of size 700, which is longer than the specified 500
Created a chunk of size 1225, which is longer than the specified 500
Created a chunk of size 658, which is longer than the specified 500
Created a chunk of size 768, which is longer than the specified 500
Created a chunk of size 554, which is longer than the specified 500
Created a chunk of size 591, which is longer than the specified 500
Created a chunk of size 727, which is longer than the specified 500
Created a chunk of size 1806, which is longer than the specified 500
Created a chunk of size 1018, which is longer than the specified 500
Created a chunk of size 685, which is longer than the specified 500
Created a chunk of size 740, which is longer than the specified 500
Created a chunk of size 923, which is longer than the specified 500
Created a chunk of size 968, which is longer than the specified 500
Created a chunk of size 646, which is longer than the specified 500
Created a chunk of size 677, which is longer than the specified 500
Created a chunk of size 713, which is longer than the specified 500
Created a chunk of size 800, which is longer than the specified 500
Created a chunk of size 855, which is longer than the specified 500
Created a chunk of size 671, which is longer than the specified 500
Created a chunk of size 855, which is longer than the specified 500
Created a chunk of size 761, which is longer than the specified 500
Created a chunk of size 797, which is longer than the specified 500
Created a chunk of size 680, which is longer than the specified 500
Created a chunk of size 928, which is longer than the specified 500
Created a chunk of size 1269, which is longer than the specified 500
Created a chunk of size 734, which is longer than the specified 500
Created a chunk of size 869, which is longer than the specified 500
Created a chunk of size 932, which is longer than the specified 500
Created a chunk of size 773, which is longer than the specified 500
Created a chunk of size 771, which is longer than the specified 500
Created a chunk of size 650, which is longer than the specified 500
Created a chunk of size 1772, which is longer than the specified 500
Created a chunk of size 535, which is longer than the specified 500
Created a chunk of size 825, which is longer than the specified 500
Created a chunk of size 600, which is longer than the specified 500
Created a chunk of size 970, which is longer than the specified 500
Created a chunk of size 555, which is longer than the specified 500
Created a chunk of size 845, which is longer than the specified 500
Created a chunk of size 877, which is longer than the specified 500
Created a chunk of size 671, which is longer than the specified 500
Created a chunk of size 708, which is longer than the specified 500
Created a chunk of size 655, which is longer than the specified 500
Created a chunk of size 1271, which is longer than the specified 500
Created a chunk of size 737, which is longer than the specified 500
Created a chunk of size 1020, which is longer than the specified 500
Created a chunk of size 778, which is longer than the specified 500
Created a chunk of size 683, which is longer than the specified 500
Created a chunk of size 599, which is longer than the specified 500
Created a chunk of size 664, which is longer than the specified 500
Created a chunk of size 596, which is longer than the specified 500
Created a chunk of size 858, which is longer than the specified 500
Created a chunk of size 596, which is longer than the specified 500
Created a chunk of size 538, which is longer than the specified 500
Created a chunk of size 568, which is longer than the specified 500
Created a chunk of size 706, which is longer than the specified 500
Created a chunk of size 849, which is longer than the specified 500
Created a chunk of size 543, which is longer than the specified 500
Created a chunk of size 1178, which is longer than the specified 500
Created a chunk of size 905, which is longer than the specified 500
Created a chunk of size 853, which is longer than the specified 500
Created a chunk of size 508, which is longer than the specified 500
Created a chunk of size 1716, which is longer than the specified 500
Created a chunk of size 846, which is longer than the specified 500
Created a chunk of size 1682, which is longer than the specified 500
Created a chunk of size 722, which is longer than the specified 500
Created a chunk of size 660, which is longer than the specified 500
Created a chunk of size 604, which is longer than the specified 500
Created a chunk of size 992, which is longer than the specified 500
Created a chunk of size 1129, which is longer than the specified 500
Created a chunk of size 2006, which is longer than the specified 500
Created a chunk of size 1172, which is longer than the specified 500
Created a chunk of size 2142, which is longer than the specified 500
Created a chunk of size 663, which is longer than the specified 500
Created a chunk of size 1323, which is longer than the specified 500
Created a chunk of size 527, which is longer than the specified 500
Created a chunk of size 1113, which is longer than the specified 500
Created a chunk of size 665, which is longer than the specified 500
Created a chunk of size 909, which is longer than the specified 500
Created a chunk of size 1317, which is longer than the specified 500
Created a chunk of size 692, which is longer than the specified 500
Created a chunk of size 951, which is longer than the specified 500
Created a chunk of size 1122, which is longer than the specified 500
Created a chunk of size 777, which is longer than the specified 500
Created a chunk of size 616, which is longer than the specified 500
Created a chunk of size 534, which is longer than the specified 500
Created a chunk of size 1019, which is longer than the specified 500
Created a chunk of size 726, which is longer than the specified 500
Created a chunk of size 613, which is longer than the specified 500
Created a chunk of size 630, which is longer than the specified 500
Created a chunk of size 1008, which is longer than the specified 500
Created a chunk of size 617, which is longer than the specified 500
Created a chunk of size 885, which is longer than the specified 500
Created a chunk of size 580, which is longer than the specified 500
Created a chunk of size 912, which is longer than the specified 500
Created a chunk of size 1058, which is longer than the specified 500
Created a chunk of size 631, which is longer than the specified 500
Created a chunk of size 1256, which is longer than the specified 500
Created a chunk of size 573, which is longer than the specified 500
Created a chunk of size 1099, which is longer than the specified 500
Created a chunk of size 908, which is longer than the specified 500
Created a chunk of size 622, which is longer than the specified 500
Created a chunk of size 878, which is longer than the specified 500
Created a chunk of size 1144, which is longer than the specified 500

In [14]:
documents[0]

Document(metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content='9780002005883: A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [16]:
db_books = Chroma.from_documents(documents,
                                 embeddings)

In [17]:
query = "A book about psychology"
docs = db_books.similarity_search(query, k=10)
docs

[Document(id='b30516d3-736d-4bbf-b6dc-d16cddbab4a0', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content='"9781593851170: ""Comprehensive and up to date, this tightly edited volume belongs on the desks of researchers and students in developmental psychology, comparative psychology, animal behavior, and evolutionary psychology, and will also be of interest to anthropologists. It is a richly informative text for advanced undergraduate- and graduate-level courses.""--BOOK JACKET."'),
 Document(id='f527e160-b000-47b7-a719-d56ff66eef63', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content="9780345487421: A psychotherapist shows how to identify the fears that are inhibiting one's life, ranging from public speaking and intimacy to aging and rejection, and how to transform frustration and helplessness into power to create success in every aspect of life, in a twentieth anniversary edition of the best-selling guide. Reissue. 50,000 first printing."),
 Document(id='0168b18e-0b1a-485e-a6dc-088d91238633', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content='"9781400095414: Two young men--student rabbi Reuven Malter and his old friend, Danny Saunders, who has abandoned his Hasidic traditions to become a psychologist--question the ""orthodoxy"" of values and religion in a world cut off from their Hasidic traditions. Reprint. 10,000 first printing."'),
 Document(id='4bdb8d89-7a93-454b-b8bf-81382b519cc6', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content='"9780300000894: A noted psychoanalyst assesses the modern issue between traditional religion and a philosophy that takes as the sole aim in life the satisfaction of instinctive and material values. ""A daring book to have cast into the midst of the world\'s excitements, for it will itself breed new excitements...it is not a book to be missed by those interested in man\'s spiritual growth.""--New York Times"'),
 Document(id='ce816d6a-34b5-44cb-8bcf-36257c207395', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content="9780684832401: Drawing from religion and the human sciences, particularly psychology after Freud, the author attempts to demonstrate that the fear of death is man's central concern"),
 Document(id='2fff5cb3-b103-42ba-ba0d-581aba9789ac', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content="9780618057078: At the heart of this classic, seminal book is Julian Jaynes's still-controversial thesis that human consciousness did not begin far back in animal evolution but instead is a learned process that came about only three thousand years ago and is still developing. The implications of this revolutionary scientific paradigm extend into virtually every aspect of our psychology, our history and culture, our religion -- and indeed our future."),
 Document(id='6442a570-27f6-48f2-a81a-2b26e9f434ff', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content='9780330346511: In this book, a world authority on manic-depression reveals her own struggle since girlhood with this cruel disease. She describes how she mastered it and how it shaped her life.'),
 Document(id='61e5898c-f5b7-40c0-98a2-0522341bf35e', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content='9780374271077: First acclaimed as a story-length memoir, then expanded into a novel, Sylvia draws us into the lives of a young couple whose struggle to survive Manhattan in the early 1960s involves them in sexual fantasias, paranoia, drugs, and the extreme intimacy of self-destructive violence. Reproducing a time and place with extraordinary clarity, Leonard Michaels explores with self-wounding honesty the excruciating particulars of a youthful marriage headed for disaster.'),
 Document(id='32134065-dbf6-49a4-8c29-e2aad44048c8', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content='9780140128468: Contains eight case-studies of people the author has treated, including a woman of 67, obsessively pining with love for her 32-year-old previous therapist and a woman of 19 stone who has emotional difficulties because of her weight problem. This title includes stories that reveal the diversity of human motivation.'),
 Document(id='03876bb2-10ce-487b-b005-4dd91653e1ad', metadata={'source': 'C:/Users/USER/PycharmProjects/Semantic_book_recommender/tagged_description.txt'}, page_content='9780471133124: A study of crowd behavior includes two landmark books of the past, Extraordinary Popular Delusions and the Madness of Crowds and Confusions de Confusions, that show how markets are shaped by the fluctuations of mob psychology. Reprint.')]

In [19]:
import re

isbn = re.findall(r"\d+", docs[0].page_content)[0]

books[books["isbn13"] == int(isbn)]

#books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
4898,9781593851170,1593851170,The Nature of Play,Anthony D. Pellegrini;Peter K. Smith,Psychology,http://books.google.com/books/content?id=Nukz6...,"""Comprehensive and up to date, this tightly ed...",2005.0,4.25,308.0,4.0,The Nature of Play: Great Apes and Humans,"9781593851170: ""Comprehensive and up to date, ..."

In [23]:
import re
import pandas as pd

def retrieve_semantic_recommendations(query: str, top_k: int = 10) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k=50)

    books_list = []
    for r in recs:
        isbn = re.findall(r"\d+", r.page_content)[0]
        books_list.append(int(isbn))

    return books[books["isbn13"].isin(books_list)].head(top_k)

In [24]:
retrieve_semantic_recommendations("A book about neuroscience")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
94,9780060084387,0060084383,Modern Mind,Peter Watson,Science,http://books.google.com/books/content?id=JVdMS...,"From Freud to Babbitt, from Animal Farm to Sar...",2002.0,4.27,847.0,570.0,Modern Mind: An Intellectual History of the 20...,"9780060084387: From Freud to Babbitt, from Ani..."
101,9780060175641,0060175648,Identity,Milan Kundera,Fiction,http://books.google.com/books/content?id=D30Ex...,Milan Kundera's Identity translated from the F...,1998.0,3.68,176.0,260.0,Identity: A Novel,9780060175641: Milan Kundera's Identity transl...
113,9780060507404,0060507403,The Cheese Monkeys,Chip Kidd,Fiction,http://books.google.com/books/content?id=wkCm2...,"After 15 years of designing more than 1,500 bo...",2002.0,3.75,288.0,4570.0,The Cheese Monkeys: A Novel in Two Semesters,9780060507404: After 15 years of designing mor...
152,9780060570583,006057058X,The Perennial Philosophy,Aldous Huxley,Philosophy,http://books.google.com/books/content?id=YdaFE...,The Perennial Philosophy is defined by its aut...,2004.0,4.23,336.0,2959.0,The Perennial Philosophy,9780060570583: The Perennial Philosophy is def...
177,9780060595180,0060595183,The Doors of Perception and Heaven and Hell,Aldous Huxley,Philosophy,http://books.google.com/books/content?id=rz3NJ...,The acclaimed novelist and critic describes hi...,2004.0,3.94,187.0,27716.0,The Doors of Perception and Heaven and Hell,9780060595180: The acclaimed novelist and crit...
292,9780060925758,0060925752,Soul Mates,Thomas Moore,Psychology,http://books.google.com/books/content?id=7syEl...,This companion volume to Care of the Soul offe...,1994.0,4.00,288.0,4122.0,Soul Mates,9780060925758: This companion volume to Care o...
301,9780060930318,0060930314,Identity,Milan Kundera,Fiction,http://books.google.com/books/content?id=mXPU2...,There are situations in which we fail for a mo...,1999.0,3.68,168.0,13065.0,Identity: A Novel,9780060930318: There are situations in which w...
313,9780060936501,0060936509,The Best American Science Writing 2002,Matt Ridley;Alan Lightman,Science,http://books.google.com/books/content?id=p8yA_...,"If, as Matt Ridley suggests, science is simply...",2002.0,3.88,352.0,66.0,The Best American Science Writing 2002,"9780060936501: If, as Matt Ridley suggests, sc..."
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,Racso and the Rats of NIMH,"9780064402453: ‘Racso, a brash and boastful li..."
600,9780140244915,0140244913,How the Mind Works,Steven Pinker,Philosophy,http://books.google.com/books/content?id=O521D...,"""Presented with extraordinary lucidity, cogenc...",1999.0,3.97,660.0,225.0,How the Mind Works,"9780140244915: ""Presented with extraordinary l..."